### ISSUE TITLE
Title update 13, Live Editor working but not working properly. 

### ISSUE THREAD

**Issue by FlapJack54** [xAranaktu/FC-24-Live-Editor#144]
When opened with Live editor EA blocks some Features like saving a game. how am I solve this, Thank you in advance.

**Comment by FlapJack54** [comment]
By the way I am using LE v24.1.1.5

**Comment by xAranaktu** [comment]
Never heard about issue like that. No known fix.

**Comment by FlapJack54** [comment]
![Ekran görüntüsü 2024-05-07 191228](https://github.com/xAranaktu/FC-24-Live-Editor/assets/169076728/031da382-98d8-4657-ac4f-d84b890e93d6)
![Ekran görüntüsü 2024-05-07 191912](https://github.com/xAranaktu/FC-24-Live-Editor/assets/169076728/08a0493f-fe6e-48c8-9c51-0ddb43867bc0)



I bought the game just for your program, because it made the game more freedom, I would be happy if you could help me with this.

**Comment by FlapJack54** [comment]
This error mostly appears.

![Ekran görüntüsü 2024-05-07 194124](https://github.com/xAranaktu/FC-24-Live-Editor/assets/169076728/681a60ae-7fa7-47cb-b8af-3d8310b8bbd2)

**Comment by FlapJack54** [comment]
Here is Log files
[log_07-05-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/15238617/log_07-05-2024.txt)
[log_launcher_07-05-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/15238618/log_launcher_07-05-2024.txt)

**Comment by xAranaktu** [comment]
> "Some features have been disabled because the EA App launched from another application."

I don't know what's that. I've never seen this before. It's not an issue with Live Editor. Try to google the error to find the solution. I can't help with that.

>  "Cannot be saved"

Your game is blocked in Windows defender. Read -> https://github.com/xAranaktu/FC-24-Live-Editor/issues/45

> "Live Editor wasn't able to find stable game process"

It's I assume related to the first error. Your game doesn't start at all and it's also not related to live editor. You can try to run the game from EA App instead of pressing "Run Game" button in live editor launcher. Sometimes it help.

**Comment by FlapJack54** [comment]
Ok, I am gonna try this, thanks for help Pavel. Good day to you.

**Comment by FlapJack54** [comment]
Finally did it Thank you so much, this mean a lot, Bless You Mate
