### ISSUE TITLE
No public releases?

### ISSUE THREAD

**Issue by Swaggyp889** [xAranaktu/FC-24-Live-Editor#6]
From the spreadsheet provided, it shows there should be 2 versions out for the public but I don't see any released on here yet. What's going on with that?

**Comment by xAranaktu** [comment]
First of all you can download these version from Patreon. Posts are public, you don't even need to register.
That being said after TU2 only v24.1.0.3 and newer versions of the tool are working. If I'll add not working version to releases guess what will happen? 10 comments daily that "Live Editor doesn't work". I don't have time for that. I don't plan to post anything under GitHub  "Releases" this year because people have problem with reading.

**Comment by jfxrbes** [comment]
so all releases will be through your patron?

**Comment by xAranaktu** [comment]
yes
