### ISSUE TITLE
I'm sorry I lost respect for you .

### ISSUE THREAD

**Issue by YGTKMN** [xAranaktu/FC-24-Live-Editor#79]
As a user who has been using Aranaktu's mods for many years, I do not want to be misunderstood.
I respect that you make money from this.
But I'm annoyed that you're excluding free users so much.
When you offer the mod to free users, the game gets an update within 4 or 5 days at most and we cannot use your mod.
Even though I respect the money you make and the work you do, this is unethical my friend.
I suggest you at least make a mod that will allow us to use cheat table only for free users.
Because I am not a modder who adds in-game faces etc. I only use live editor and cheat table for career mode.
But every time you release a mod, an update comes to the game within 4 days at most and we have to wait another 10-15 days.I hope you listen and take it seriously.
Best regards to free users

**Comment by xAranaktu** [comment]
If you play this game for many years then you should know what happened 1 year ago and why things are how they are right now.
EA decided to add the anticheat to this game and now it's endless cat and mouse game.
I've created EAAC bypass -> EA Update the EAAC breaking my EAAC bypass -> I update the bypass -> they update the EAAC... this circle will never end
Each game update most of the time forces me to update the eaac bypass. Not working bypass is that what makes the live editor not working.
So no, I can't create "a mod that will allow us to use cheat table" because to use cheat engine you need to bypass the anticheat. 
It's not my fault that EA update the game so frequently.
